version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/domainr/dnsr
    docker:
      - image: domainr/ci:swan
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v

      # Run tests
      - run: mkdir -p test-results
      - run: |
          trap "go-junit-report < test-results/go-test.log > test-results/go-test-report.xml" EXIT
          go test -v -race -bench . ./... | tee test-results/go-test.log

      # Report
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: results

  update:
    working_directory: ~/go/src/github.com/domainr/dnsr
    docker:
      - image: domainr/ci:swan
        environment:
          GIT_AUTHOR_EMAIL: robot@domainr.com
          GIT_AUTHOR_NAME: Domainr Robot
          GIT_COMMITTER_EMAIL: robot@domainr.com
          GIT_COMMITTER_NAME: Domainr Robot
    steps:
      - checkout
      - run: go get -t -d ./...
      - run: go generate
      - run: go test ./...
      - run: |
          git diff-index --quiet HEAD -- || (\
            git add --all . && \
            git commit -m "auto-update" && \
            git push origin $CIRCLE_BRANCH \
          )

workflows:
  version: 2
  commit_workflow:
    jobs:
      - build
  scheduled_workflow:
    jobs:
      - update
    triggers:
      # Circle operates in UTC. 12:13 AM PST is 8:13 AM UTC
      - schedule:
          cron: "13 8 * * *"
          filters:
            branches:
              only:
                - master
